# -*- mode: ruby -*-
# vi: set ft=ruby :

# *Variables
provider     = "libvirt"
# vm configuration
memory       = 2048
cpu          = 2
# vagrant data location
vagrant_home ="/mnt/ext/vagrant.d"

# *VMs spec
vm_boxes = {
  "rhel" => {
    :box => "generic/rhel8",
    :ip => "192.168.33.11",
    :script => <<~SCRIPT
      dnf install -y bash-completion
    SCRIPT
  },
  "centos" => {
    :box => "generic/centos8s",
    :ip => "192.168.33.12",
    :script => <<~SCRIPT
      dnf install -y ansible
    SCRIPT
  },
  "ubuntu" => {
    :box => "generic/ubuntu2204",
    :ip => "192.168.33.13",
    :script => <<~SCRIPT
      export DEBIAN_FRONTEND=noninteractive && apt-add-repository -y ppa:ansible/ansible && apt-get install -qy ansible
    SCRIPT
  }
}

# *VM provisioning
Vagrant.configure("2") do |config|
  # common config
  config.vm.provider provider do |v|
    v.memory = memory
    v.cpus = cpu
  end
  vm_boxes.each do |key, value|
    ip_addr = value[:ip]
    config.vm.define key do |node|
      # node triggers
      node.trigger.after :reload do |trigger|
        trigger.info = "Add vagrant configuration to ssh config file..."
        trigger.run = { privileged: "false", path: "../../.assets/trigger/set_ssh_config.sh", :args => [ip_addr] }
      end
      # node setup
      node.vm.box = value[:box]
      node.vm.hostname = key
      node.vm.network "private_network", ip: ip_addr
      # node provision
      node.vm.provision "ansible", playbook: "../../.assets/playbooks/user_create.yaml"
      node.vm.provision "shell", name: "install packages...", inline: value[:script]
      # ~reload vm
      node.vm.provision :reload
    end
  end
end
