# -*- mode: ruby -*-
# vi: set ft=ruby :

# *Variables
provider     = "libvirt"
# vm configuration
memory       = 2048
cpu          = 2
# vagrant data location
vagrant_home ="/mnt/ext/vagrant.d"

# *VMs spec
vm_boxes = {
  "rhel" => {
    :ip => "192.168.33.11",
    :box => "generic/rhel8",
    :script_packages => "dnf install -y bash-completion",
  },
  "centos" => {
    :ip => "192.168.33.12",
    :box => "generic/centos8s",
    :script_packages => "dnf install -y ansible-core",
  },
  "ubuntu" => {
    :ip => "192.168.33.13",
    :box => "generic/ubuntu2004",
    :script_packages => "export DEBIAN_FRONTEND=noninteractive && apt-get install -qy ansible",
  }
}

# *VM provisioning
Vagrant.configure("2") do |config|
  # common config
  config.vm.provider provider do |v|
    v.memory = memory
    v.cpus = cpu
  end
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  config.ssh.private_key_path = ["~/.ssh/id_rsa", "#{vagrant_home}/insecure_private_key"]
  config.ssh.insert_key = false
  vm_boxes.each do |key, value|
    ip_addr = value[:ip]
    config.vm.define key do |node|
      # node triggers
      node.trigger.after :reload do |trigger|
        trigger.info = "Add vagrant configuration to ssh config file..."
        trigger.run = { privileged: "false", path: "../../.assets/trigger/set_ssh_config.sh", :args => [ip_addr] }
      end
      # node setup
      node.vm.box = value[:box]
      node.vm.hostname = key
      node.vm.network "private_network", ip: ip_addr
      # node provision
      node.vm.provision "ansible", playbook: "../../.assets/playbooks/user_create.yaml"
      node.vm.provision "shell", name: "install packages...", inline: value[:script_packages]
      node.vm.provision :reload
    end
  end
end
